### ISSUE TITLE
Got `MIME type ('application/json') is not executable` when perform JSOP request

### ISSUE THREAD

**Issue by mazipan** [RekingZhang/axios-jsonp#1]
Got this error when using jsop : 

Refused to execute script from 'https://sites.google.com/macros/exec?service=AKfycbx_-gZbLP7Z2gGxehXhWMWDAAQsTp3e3bmpTBiaLuzSDQSbIFWD&menu=nama_produk&query=abc&callback=__jp0&_=1513598105820' because its MIME type ('application/json') is not executable, and strict MIME type checking is enabled.

this is snippet my code : 

```
axios
          .jsonp(path)
          .then((response) => {
            console.log('Success when getting data via API ', response)
          })
          .catch((error) => {
            console.log('Error when trying to get via API ', error)
          })
```

**Comment by RekingZhang** [comment]
The return value of the interface must be  a callback function , like this :  cb({"a":1,"b":2});

**Comment by jjhesk** [comment]
@RekingZhang according the error that is something related to the headers issue. how do you fix that?

**Comment by jjhesk** [comment]
i had the same issue like @mazipan do. thanks

**Comment by jjhesk** [comment]
when the callback is _jp0 does it handled internally in the library?

**Comment by RekingZhang** [comment]
https://stackoverflow.com/questions/2067472/what-is-jsonp-all-about/2067584#2067584?newreg=d2d8726b175d4051a32a3ab771b9a0cd

**Comment by RekingZhang** [comment]
https://stackoverflow.com/questions/2067472/what-is-jsonp-all-about/2067584#2067584?newreg=d2d8726b175d4051a32a3ab771b9a0cd

**Comment by RekingZhang** [comment]
https://stackoverflow.com/questions/2067472/what-is-jsonp-all-about/2067584#2067584?newreg=d2d8726b175d4051a32a3ab771b9a0cd

**Comment by RekingZhang** [comment]
@jjhesk  You should know JSONP    https://stackoverflow.com/questions/2067472/what-is-jsonp-all-about/2067584#2067584?newreg=d2d8726b175d4051a32a3ab771b9a0cd
